# templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snakecicd-storage
  namespace: snakecicd-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path

