falco:
  jsonOutput: true
  logLevel: info

  httpOutput:
    enabled: true
    url: "http://falco-falcosidekick:2801"

  grpc:
    enabled: false

falcosidekick:
  enabled: true
  fullfqdn: false
  replicaCount: 1

  config:
    prometheus:
      enabled: true
      endpoint: "0.0.0.0:2802"

  service:
    type: ClusterIP
    ports:
      - name: http
        port: 2801
        targetPort: 2801
      - name: http-metrics
        port: 2802
        targetPort: 2802

  env:
    - name: PROMETHEUS
      value: "true"

rbac:
  create: true

serviceAccount:
  create: true

