falco:
  jsonOutput: true
  logLevel: info
  httpOutput:
    enabled: true
    url: "http://falco-falcosidekick.default.svc.cluster.local:2801"
  grpc:
    enabled: false

falcosidekick:
  enabled: true
  fullfqdn: false
  replicaCount: 1

  config:
    prometheus:
      enabled: true
      endpoint: "0.0.0.0:2802"
    customfields:
      output: "prometheus"

  service:
    type: ClusterIP
    ports:
      - name: http
        port: 2801
        targetPort: 2801
      - name: http-metrics
        port: 2802
        targetPort: 2802

  env:
    - name: PROMETHEUS
      value: "true"
    - name: DEBUG
      value: "true"  # Dodaj tymczasowo dla lepszych logów

rbac:
  create: true

serviceAccount:
  create: true

