versionapp: 66

replicaCount: 2

resources:
  requests:
    cpu: 50m
    memory: 100Mi
  limits:
    cpu: 100m
    memory: 200Mi

highscore:
  scores: |
    Daniel zdobyl 11300 punktów
    Marta zdobyla 100 punktów
    Tomek zdobyl 50 punktów
